//! Proof-of-work stamp generation and validation.
//!
//! The stamper module provides proof-of-work based rate limiting for LXMF messages
//! and interface discovery. Stamps are 32-byte values that, when concatenated with
//! a workblock and hashed, produce a result with a specified number of leading zero bits.
//!
//! # Algorithm
//!
//! 1. A workblock is generated by expanding the input material through HKDF over multiple rounds.
//! 2. A valid stamp is one where `SHA256(workblock || stamp)` has at least `target_cost` leading zero bits.
//! 3. Stamps are found through random search, making generation computationally expensive.
//!
//! # Usage
//!
//! ```rust
//! use std::sync::atomic::AtomicBool;
//! use std::sync::Arc;
//! use reticulum::stamper::{Stamper, WORKBLOCK_EXPAND_ROUNDS_PEERING};
//!
//! // Generate a stamp with low difficulty (for testing)
//! let message_id = b"test_message_id";
//! let cancel = Arc::new(AtomicBool::new(false));
//! let result = Stamper::generate_stamp(message_id, 4, WORKBLOCK_EXPAND_ROUNDS_PEERING, cancel);
//!
//! if let Ok((stamp, value)) = result {
//!     println!("Generated stamp with value {}", value);
//! }
//! ```

use crate::error::RnsError;
use hkdf::Hkdf;
use rand::{CryptoRng, RngCore};
use rayon::prelude::*;
use sha2::{Digest, Sha256};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

/// Standard expand rounds for regular message stamps.
pub const WORKBLOCK_EXPAND_ROUNDS: u32 = 3000;

/// Expand rounds for propagation node stamps (lower for faster validation).
pub const WORKBLOCK_EXPAND_ROUNDS_PN: u32 = 1000;

/// Expand rounds for peering key generation (lowest for interactive use).
pub const WORKBLOCK_EXPAND_ROUNDS_PEERING: u32 = 25;

/// Expand rounds for interface discovery (per Python's Discovery.py).
pub const WORKBLOCK_EXPAND_ROUNDS_DISCOVERY: u32 = 20;

/// Stamp size in bytes (256 bits / 8).
pub const STAMP_SIZE: usize = 32;

/// Minimum list size before using parallel validation.
pub const PN_VALIDATION_POOL_MIN_SIZE: usize = 256;

/// Default stamp value required for discovery announcements.
pub const DEFAULT_DISCOVERY_STAMP_VALUE: u8 = 14;

/// Stamper provides proof-of-work stamp generation and validation.
///
/// This is a stateless utility struct - all methods are static.
pub struct Stamper;

impl Stamper {
    /// Generate a workblock by expanding the material through HKDF.
    ///
    /// The workblock is generated by performing `expand_rounds` iterations of HKDF,
    /// each producing 256 bytes, concatenated together.
    ///
    /// # Arguments
    /// * `material` - The input material (typically a message ID or info hash).
    /// * `expand_rounds` - Number of HKDF expansion rounds.
    ///
    /// # Returns
    /// The generated workblock (expand_rounds * 256 bytes).
    pub fn stamp_workblock(material: &[u8], expand_rounds: u32) -> Vec<u8> {
        let mut workblock = Vec::with_capacity(expand_rounds as usize * 256);

        for n in 0..expand_rounds {
            // Create salt: full_hash(material + msgpack(n))
            let n_packed = rmp_serde::to_vec(&n).unwrap_or_else(|_| vec![]);
            let mut salt_material = Vec::with_capacity(material.len() + n_packed.len());
            salt_material.extend_from_slice(material);
            salt_material.extend_from_slice(&n_packed);

            let salt = Self::full_hash(&salt_material);

            // HKDF expand with salt
            let hk = Hkdf::<Sha256>::new(Some(&salt), material);
            let mut okm = [0u8; 256];
            // Using empty info as context is None in Python
            hk.expand(&[], &mut okm)
                .expect("HKDF expand should not fail for 256 bytes");
            workblock.extend_from_slice(&okm);
        }

        workblock
    }

    /// Calculate the stamp value (number of leading zero bits in the result).
    ///
    /// # Arguments
    /// * `workblock` - The workblock to validate against.
    /// * `stamp` - The stamp to evaluate.
    ///
    /// # Returns
    /// The number of leading zero bits in SHA256(workblock || stamp).
    pub fn stamp_value(workblock: &[u8], stamp: &[u8]) -> u8 {
        let mut material = Vec::with_capacity(workblock.len() + stamp.len());
        material.extend_from_slice(workblock);
        material.extend_from_slice(stamp);

        let hash = Self::full_hash(&material);

        // Count leading zero bits
        let mut value = 0u8;
        for byte in hash {
            if byte == 0 {
                value += 8;
            } else {
                // Count leading zeros in this byte
                value += byte.leading_zeros() as u8;
                break;
            }
        }

        value
    }

    /// Check if a stamp meets the target difficulty.
    ///
    /// A stamp is valid if SHA256(workblock || stamp) interpreted as a big-endian
    /// integer is <= 2^(256 - target_cost), i.e., has at least `target_cost` leading zero bits.
    ///
    /// # Arguments
    /// * `stamp` - The stamp to validate.
    /// * `target_cost` - Required number of leading zero bits.
    /// * `workblock` - The workblock to validate against.
    ///
    /// # Returns
    /// `true` if the stamp is valid, `false` otherwise.
    pub fn stamp_valid(stamp: &[u8], target_cost: u8, workblock: &[u8]) -> bool {
        if target_cost == 0 {
            return true;
        }

        // Check if result <= 2^(256 - target_cost)
        // This is equivalent to checking that the first `target_cost` bits are zero
        Self::stamp_value(workblock, stamp) >= target_cost
    }

    /// Validate a peering key against the required cost.
    ///
    /// # Arguments
    /// * `peering_id` - The peering identity material.
    /// * `peering_key` - The peering key (stamp) to validate.
    /// * `target_cost` - Required difficulty.
    ///
    /// # Returns
    /// `true` if the peering key is valid, `false` otherwise.
    pub fn validate_peering_key(peering_id: &[u8], peering_key: &[u8], target_cost: u8) -> bool {
        let workblock = Self::stamp_workblock(peering_id, WORKBLOCK_EXPAND_ROUNDS_PEERING);
        Self::stamp_valid(peering_key, target_cost, &workblock)
    }

    /// Validate a discovery stamp against the required cost.
    ///
    /// # Arguments
    /// * `info_hash` - The hash of the discovery info data.
    /// * `stamp` - The stamp to validate.
    /// * `target_cost` - Required difficulty.
    ///
    /// # Returns
    /// `true` if the stamp is valid, `false` otherwise.
    pub fn validate_discovery_stamp(info_hash: &[u8], stamp: &[u8], target_cost: u8) -> bool {
        let workblock = Self::stamp_workblock(info_hash, WORKBLOCK_EXPAND_ROUNDS_DISCOVERY);
        Self::stamp_valid(stamp, target_cost, &workblock)
    }

    /// Generate a stamp meeting the target difficulty.
    ///
    /// This function uses parallel processing via rayon to search for a valid stamp.
    /// The search can be cancelled by setting the `cancel` flag.
    ///
    /// # Arguments
    /// * `message_id` - The message ID to generate a stamp for.
    /// * `stamp_cost` - Required number of leading zero bits.
    /// * `expand_rounds` - HKDF expansion rounds for workblock generation.
    /// * `cancel` - Atomic flag to cancel the operation.
    ///
    /// # Returns
    /// A tuple of (stamp, achieved_value) on success.
    pub fn generate_stamp(
        message_id: &[u8],
        stamp_cost: u8,
        expand_rounds: u32,
        cancel: Arc<AtomicBool>,
    ) -> Result<(Vec<u8>, u8), RnsError> {
        let workblock = Self::stamp_workblock(message_id, expand_rounds);
        Self::generate_stamp_with_workblock(&workblock, stamp_cost, cancel)
    }

    /// Generate a stamp with a pre-computed workblock.
    ///
    /// # Arguments
    /// * `workblock` - The pre-computed workblock.
    /// * `stamp_cost` - Required number of leading zero bits.
    /// * `cancel` - Atomic flag to cancel the operation.
    ///
    /// # Returns
    /// A tuple of (stamp, achieved_value) on success.
    pub fn generate_stamp_with_workblock(
        workblock: &[u8],
        stamp_cost: u8,
        cancel: Arc<AtomicBool>,
    ) -> Result<(Vec<u8>, u8), RnsError> {
        // Use rayon for parallel search
        let num_threads = rayon::current_num_threads();

        // Each thread searches independently
        let result = (0..num_threads).into_par_iter().find_map_any(|_| {
            let mut rng = rand::thread_rng();
            Self::search_stamp(&mut rng, workblock, stamp_cost, &cancel)
        });

        match result {
            Some((stamp, value)) => Ok((stamp, value)),
            None => {
                if cancel.load(Ordering::Relaxed) {
                    Err(RnsError::Cancelled)
                } else {
                    // This shouldn't happen in practice
                    Err(RnsError::CryptoError)
                }
            }
        }
    }

    /// Async wrapper around `generate_stamp` that offloads CPU-bound work
    /// to a blocking thread pool, keeping the async runtime responsive.
    pub async fn generate_stamp_async(
        message_id: Vec<u8>,
        stamp_cost: u8,
        expand_rounds: u32,
        cancel: Arc<AtomicBool>,
    ) -> Result<(Vec<u8>, u8), RnsError> {
        tokio::task::spawn_blocking(move || {
            Self::generate_stamp(&message_id, stamp_cost, expand_rounds, cancel)
        })
        .await
        .map_err(|_| RnsError::CryptoError)?
    }

    /// Async wrapper around `generate_stamp_with_workblock` that offloads
    /// CPU-bound work to a blocking thread pool.
    pub async fn generate_stamp_with_workblock_async(
        workblock: Vec<u8>,
        stamp_cost: u8,
        cancel: Arc<AtomicBool>,
    ) -> Result<(Vec<u8>, u8), RnsError> {
        tokio::task::spawn_blocking(move || {
            Self::generate_stamp_with_workblock(&workblock, stamp_cost, cancel)
        })
        .await
        .map_err(|_| RnsError::CryptoError)?
    }

    /// Search for a valid stamp (internal function).
    fn search_stamp<R: RngCore + CryptoRng>(
        rng: &mut R,
        workblock: &[u8],
        target_cost: u8,
        cancel: &AtomicBool,
    ) -> Option<(Vec<u8>, u8)> {
        let mut stamp = [0u8; STAMP_SIZE];
        let mut rounds = 0u64;

        loop {
            if cancel.load(Ordering::Relaxed) {
                return None;
            }

            // Generate random stamp
            rng.fill_bytes(&mut stamp);
            rounds += 1;

            // Check if valid
            if Self::stamp_valid(&stamp, target_cost, workblock) {
                let value = Self::stamp_value(workblock, &stamp);
                return Some((stamp.to_vec(), value));
            }

            // Periodically check cancel flag (every 1000 rounds)
            if rounds % 1000 == 0 && cancel.load(Ordering::Relaxed) {
                return None;
            }
        }
    }

    /// Validate a propagation node stamp.
    ///
    /// # Arguments
    /// * `transient_data` - The full message data including stamp.
    /// * `target_cost` - Required stamp difficulty.
    ///
    /// # Returns
    /// Tuple of (transient_id, lxm_data, stamp_value, stamp) or None if invalid.
    #[allow(clippy::type_complexity)]
    pub fn validate_pn_stamp(
        transient_data: &[u8],
        target_cost: u8,
    ) -> Option<(Vec<u8>, Vec<u8>, u8, Vec<u8>)> {
        // LXMF_OVERHEAD is 112 bytes (defined in message module)
        const LXMF_OVERHEAD: usize = 112;

        if transient_data.len() <= LXMF_OVERHEAD + STAMP_SIZE {
            return None;
        }

        let split_point = transient_data.len() - STAMP_SIZE;
        let lxm_data = &transient_data[..split_point];
        let stamp = &transient_data[split_point..];

        let transient_id = Self::full_hash(lxm_data);
        let workblock = Self::stamp_workblock(&transient_id, WORKBLOCK_EXPAND_ROUNDS_PN);

        if !Self::stamp_valid(stamp, target_cost, &workblock) {
            return None;
        }

        let value = Self::stamp_value(&workblock, stamp);
        Some((transient_id.to_vec(), lxm_data.to_vec(), value, stamp.to_vec()))
    }

    /// Validate multiple propagation node stamps.
    ///
    /// Uses parallel processing for large lists.
    ///
    /// # Arguments
    /// * `transient_list` - List of message data with stamps.
    /// * `target_cost` - Required stamp difficulty.
    ///
    /// # Returns
    /// List of valid (transient_id, lxm_data, stamp_value, stamp) tuples.
    #[allow(clippy::type_complexity)]
    pub fn validate_pn_stamps(
        transient_list: &[Vec<u8>],
        target_cost: u8,
    ) -> Vec<(Vec<u8>, Vec<u8>, u8, Vec<u8>)> {
        if transient_list.len() <= PN_VALIDATION_POOL_MIN_SIZE {
            // Simple sequential validation
            transient_list
                .iter()
                .filter_map(|data| Self::validate_pn_stamp(data, target_cost))
                .collect()
        } else {
            // Parallel validation
            transient_list
                .par_iter()
                .filter_map(|data| Self::validate_pn_stamp(data, target_cost))
                .collect()
        }
    }

    /// Compute SHA-256 hash (full 32 bytes).
    #[inline]
    pub fn full_hash(data: &[u8]) -> [u8; 32] {
        let mut hasher = Sha256::new();
        hasher.update(data);
        hasher.finalize().into()
    }

    /// Compute truncated hash (16 bytes, for address hashes).
    #[inline]
    pub fn truncated_hash(data: &[u8]) -> [u8; 16] {
        let full = Self::full_hash(data);
        let mut truncated = [0u8; 16];
        truncated.copy_from_slice(&full[..16]);
        truncated
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stamp_workblock_deterministic() {
        let material = b"test_material";
        let wb1 = Stamper::stamp_workblock(material, 10);
        let wb2 = Stamper::stamp_workblock(material, 10);
        assert_eq!(wb1, wb2);
        assert_eq!(wb1.len(), 10 * 256);
    }

    #[test]
    fn test_stamp_value_all_zeros() {
        let workblock = vec![0u8; 256];
        // A stamp that produces all-zero hash would have value 256
        // We can't easily construct this, but we can test the counting logic
        let stamp = vec![0u8; 32];
        let value = Stamper::stamp_value(&workblock, &stamp);
        // The actual value depends on the hash - just verify it returns something
        // The value will be low since SHA256(zeros || zeros) is not zero
        assert!(value < 32); // Extremely unlikely to get 32+ leading zeros by chance
    }

    #[test]
    fn test_stamp_valid_zero_cost() {
        let workblock = vec![0u8; 256];
        let stamp = vec![0u8; 32];
        // Zero cost should always be valid
        assert!(Stamper::stamp_valid(&stamp, 0, &workblock));
    }

    #[test]
    fn test_stamp_generation_low_cost() {
        let message_id = b"test_message_id";
        let cancel = Arc::new(AtomicBool::new(false));

        // Low cost should be quick to find
        let result = Stamper::generate_stamp(message_id, 4, WORKBLOCK_EXPAND_ROUNDS_PEERING, cancel);
        assert!(result.is_ok());

        let (stamp, value) = result.unwrap();
        assert_eq!(stamp.len(), STAMP_SIZE);
        assert!(value >= 4);
    }

    #[test]
    fn test_stamp_generation_cancel() {
        let message_id = b"test_message_id";
        let cancel = Arc::new(AtomicBool::new(true)); // Pre-cancelled

        // Should return cancelled error immediately
        let result =
            Stamper::generate_stamp(message_id, 20, WORKBLOCK_EXPAND_ROUNDS_PEERING, cancel);
        assert!(matches!(result, Err(RnsError::Cancelled)));
    }

    #[test]
    fn test_full_hash() {
        let data = b"hello world";
        let hash = Stamper::full_hash(data);
        assert_eq!(hash.len(), 32);

        // SHA256("hello world") is a known value
        let expected = hex::decode("b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9")
            .unwrap();
        assert_eq!(hash[..], expected[..]);
    }

    #[test]
    fn test_truncated_hash() {
        let data = b"hello world";
        let hash = Stamper::truncated_hash(data);
        assert_eq!(hash.len(), 16);

        // Should be first 16 bytes of full hash
        let full = Stamper::full_hash(data);
        assert_eq!(hash[..], full[..16]);
    }

    #[test]
    fn test_discovery_stamp_validation() {
        // Test with pre-generated workblock
        let info_hash = b"test_discovery_info";
        let workblock = Stamper::stamp_workblock(info_hash, WORKBLOCK_EXPAND_ROUNDS_DISCOVERY);

        // Generate a stamp with low cost
        let cancel = Arc::new(AtomicBool::new(false));
        let (stamp, value) = Stamper::generate_stamp_with_workblock(&workblock, 4, cancel).unwrap();

        // Validate it
        assert!(Stamper::stamp_valid(&stamp, 4, &workblock));
        assert!(value >= 4);

        // Validate using the convenience function
        assert!(Stamper::validate_discovery_stamp(info_hash, &stamp, 4));
    }

    #[tokio::test]
    async fn test_stamp_generation_async() {
        let message_id = b"test_message_id".to_vec();
        let cancel = Arc::new(AtomicBool::new(false));

        let result = Stamper::generate_stamp_async(
            message_id,
            4,
            WORKBLOCK_EXPAND_ROUNDS_PEERING,
            cancel,
        )
        .await;
        assert!(result.is_ok());

        let (stamp, value) = result.unwrap();
        assert_eq!(stamp.len(), STAMP_SIZE);
        assert!(value >= 4);
    }

    #[tokio::test]
    async fn test_stamp_generation_async_cancel() {
        let message_id = b"test_message_id".to_vec();
        let cancel = Arc::new(AtomicBool::new(true)); // Pre-cancelled

        let result = Stamper::generate_stamp_async(
            message_id,
            20,
            WORKBLOCK_EXPAND_ROUNDS_PEERING,
            cancel,
        )
        .await;
        assert!(matches!(result, Err(RnsError::Cancelled)));
    }
}
